### ISSUE TITLE
echoplex

### ISSUE THREAD

**Issue by zhr0** [libreprojects/libreprojects#100]
https://chat.echoplex.us/

**Comment by yuwash** [comment]
- echoplex is amazing, thanks! What do some other @libreprojects/contributors think?
- defuse.ca → pastebin: [the license is not clear](https://github.com/defuse/pastebin) (so, it’s opensource but not free); additionally, we already [discussed](https://github.com/libreprojects/libreprojects/issues/8#issuecomment-30092225) about a similar software, Pastevault, but didn’t see the point of adding such a thing. We already have ownCloud and that offers encrypted storage with similarly usable web interface.
- socket.io: it is rather a library/framework that facilitates making various kinds of web apps, but the example implementations are really just for demo (not very featureful) and perhaps thus not very interesting for end users.

**Comment by airon90** [comment]
IMO you can start forking and add Echoplex

**Comment by jancborchardt** [comment]
Woah, echoplex looks like a full-blown group collaboration app – chat, code scratchpad, notepad, and voice+video calls.

@zhr0 check out the tutorial on how to add new projects: https://github.com/libreprojects/libreprojects#adding-new-projects

**Comment by jancborchardt** [comment]
@zhr0 before suggesting more projects it would be good if you can read the Readme: https://github.com/libreprojects/libreprojects/blob/gh-pages/README.md
There you will learn which projects meet the standard of Libre Projects, as well as how you can add projects yourself. If you’re »bad with Github«, everything is described there for you to easily follow.

**Comment by yuwash** [comment]
@zhr0 _(writing because of your additional suggestions)_ Please really understand the aim of this project. As a basic rule the website has to be a [free](http://fsf.org) and [opensource](http://opensource.org) (floss) project! That’s what ‘libre’ stands for.

**Comment by ironbishop** [comment]
merged
