### ISSUE TITLE
add demosphere.eu

### ISSUE THREAD

**Issue by nondidju** [libreprojects/libreprojects#101]
It's a free software and a network of activist calendars. It's developped to be collaborative and without limitations of reading. There are 30 local collectives mainly actives in Europa and but it's open to join for a new self-hosted installation or managed by the network.

http://demosphere.eu/

**Comment by jancborchardt** [comment]
Hm, it seems to be heavily focused on France though. So mostly another regional calendar.

**Comment by yuwash** [comment]
Site is obviously limited to the use for social activism anyway, though the software could be used for other purposes. Additionally, the software can be merely downloaded (with source), but it doesn’t seem to be developed collaboratively. And yes, we already have a calendar (grical).
