### ISSUE TITLE
Maqette - hosted instance isn't anymore.

### ISSUE THREAD

**Issue by lightonflux** [libreprojects/libreprojects#105]
> In May 2013, active development of the Maqetta open source project stopped, and in February 2014, the free web hosting service for the Maqetta application at Maqetta.org became unavailable.

[link](http://maqetta.org/overview/summary.htm)

**Comment by jancborchardt** [comment]
@lightonflux good catch! Can you submit a pull request which removes Maquetta from the js/data.json and the logo?
