### ISSUE TITLE
Site temporarily disabled

### ISSUE THREAD

**Issue by hugoroy** [libreprojects/libreprojects#112]
http://libreprojects.net/

see https://github.com/blog/1925-github-pages-legacy-ip-brownout

Site temporarily disabled

This page has been temporarily disabled due to a misconfigured custom domain.

Are you the site owner? Follow the instructions for setting up a custom domain with GitHub pages to update your site's DNS records to point to the proper IP address.

You can find more information in our GitHub Pages legacy IP deprecation blog post. If you have any questions, please contact support.
Contact Support — GitHub Status — @githubstatus

**Comment by jancborchardt** [comment]
Changed it, probably takes some time to propagate. Keeping this open until it’s resolved.

**Comment by jhuet** [comment]
Back to normal for me !

**Comment by jancborchardt** [comment]
Fixed, [libreprojects.net](http://libreprojects.net/) is available again. :rocket:
