### ISSUE TITLE
Add Searx (metasearch engine)

### ISSUE THREAD

**Issue by GreenLunar** [libreprojects/libreprojects#115]
Searx is a metasearch engine, inspired by the seeks project.

https://searx.me/
asciimoo/searx/issues/222

**Comment by airon90** [comment]
After reading asciimoo/searx#222 I can't be objective because I think you're spamming your product over the Internet. I let other @libreprojects/contributors decide for me.

**Comment by GreenLunar** [comment]
Sure.  I have referred to asciimoo/searx#222 so that I would not be suspected of being sneaky in regard to searx.

I would be glad to see bookie, shaarli (bookmark managers), searx (and even more) featured on libreprojects.

**Comment by jancborchardt** [comment]
I’m not sure either. We already have Seeks – what exactly are the differences, or how is Searx better?

**Comment by GreenLunar** [comment]
Localization (implemented), Skins (implemented), and DHT based search (not yet implemented) which is also in Seeks list of TODO.

Maybe this resource would be relevant.
https://about.okhin.fr/posts/Searx/

**Comment by GreenLunar** [comment]
Searx has an extensible (maybe, better maintained) set of [engines](https://github.com/asciimoo/searx/tree/master/searx/engines) (OpenStreetMap, The Pirate Bay and many more).

**Comment by dalf** [comment]
I will try to answer the question "why searx over seeks ?" as I make some contributions to Searx :
Seeks is not maintained anymore, look at : https://github.com/beniz/seeks/commits/master

If you look at https://github.com/beniz/seeks/wiki/List-of-Web-Seeks-nodes you will see that most of nodes are either dead or switch to searx instance.

Searx is "only" a proxy to different search engines, but it is up to date and written in python which help to have more contributors (there is no P2P between Searx instances).

I won't speak for @asciimoo , the main author, but feel free to include or not Searx in libreprojects.

**Comment by jancborchardt** [comment]
Ok, if Seeks is not maintained anymore then please issue a pull request replacing it with Searx. The [readme has instructions on how to do that](https://github.com/libreprojects/libreprojects#adding-new-projects). Thank you!

**Comment by GreenLunar** [comment]
No, keep Seeks.  Searx is different, not otherwise.

Seeks just needs more maintainers.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/libreprojects/libreprojects/pull/123 :)

**Comment by GreenLunar** [comment]
Please DO NOT remove Seeks!

Maybe the next enthusiastic Seeks contributor would find Seeks via LibreProjects.

**Comment by jancborchardt** [comment]
Sorry, but a long list of projects is not the focus of Libre Projects. We aim to showcase the most well-designed, active projects in a specific category. That’s also the reason we don’t have all the many »decentralized social networks« on the page.

@GreenLunar I think [Prism Break](https://prism-break.org/) has less strict guidelines what that concerns. You could add Seeks there.

**Comment by GreenLunar** [comment]
I do not know if adding new search engines to Seeks is as simple as Searx, but if it is (or when it would be possible if it is not at the moment), it would be a good decision to add Seeks alongside Searx.

The web is over centralized and spreading the word about more projects is desperately needed.

**Comment by jancborchardt** [comment]
Sorry, but if everything is important, nothing is important. We focus on adding the best solution to a specific thing. And in this case it clearly seems to be Searx over Seeks.

**Comment by GreenLunar** [comment]
Not everything. Search Engine software are special because, I believe from my experiences, these are main targets to hit by those who wish for WWW centralization.

Long time ago, Wikia was started by the infamous Wikipedia founder as a Search Engine that everyone is able to edit (add their own) links of results. Wikia, which was a good project, is no more, for no good reason whatsoever other than preserving the status quo ante.

@beniz please participate in this discussion for keeping Seeks.

---

_Added on December 17th, 2015_
I suggest to restore Seeks, and have both; you may never know whether someone would reject Searx, not knowing of Seeks, and would have accepted Seeks, otherwise.

**Comment by yuwash** [comment]
Of course I’m sure we all value multiple approaches of free search engine alternatives. We really need a more mature alternative that offers really great user experience for non-geeks and that’d hopefully get more people excited into the idea of free software. When seeks would reach some maturity and has a set of unique features to distinguish itself from other projects we’re listing like searx or Duck Duck Go, we can surely consider adding it again. For the time being, however, I’m afraid listing several similar projects would confuse non-geek visitors more than help them. It’s great work you’re doing, keep up! I’m sure there are several platforms elsewhere where you can specifically promote your projects to potential contributors.

**Comment by beniz** [comment]
@GreenLunar, all, Seeks is not being maintained, an will not (IMO ever) be again. It is time for alternatives. I have no opinion about Searx and I trust your (way more) informed judgment over mine. With other software of the same 'era', Seeks may have planted a few (hopefully widely distributed) seeds around. With some hard work (and water), a range of more mature alternatives should grow out of those first concepts, and I can't wait to see this happening. Focusing attention on the most lively projects is probably the best to do right now.

Thanks for the attention @GreenLunar, not all hopes are gone, and... hum... 'Seeds' could just be a great name for a new project in the decentralized websearch category ;)
