### ISSUE TITLE
Add Shaarli (bookmark manager)

### ISSUE THREAD

**Issue by GreenLunar** [libreprojects/libreprojects#117]
Featured in YunoHost
https://yunohost.org/
https://github.com/YunoHost

http://sebsauvage.net/wiki/doku.php?id=php:shaarli
https://github.com/sebsauvage/Shaarli
https://github.com/shaarli

**Comment by jancborchardt** [comment]
Is there a hosted instance of it?

**Comment by GreenLunar** [comment]
I do not know.

Ping @ArthurHoaro @nodiscc @Sbgodin

**Comment by nodiscc** [comment]
Hi, there is no "official" Shaarli hoster. It is meant to be single user; however some people provide Shaarli "farms" where you are able to setup your own. See https://github.com/shaarli/Shaarli/wiki#other-links. 

Note that they are based on the previous codebase: The https://github.com/sebsauvage/Shaarli repo  and original homepage http://sebsauvage.net/wiki/doku.php?id=php:shaarli are unmaintained. The community fork https://github.com/shaarli/Shaarli is where development/maintenance happens recently. See https://github.com/shaarli/shaarli#about for info on the origins of the fork.

Your contributions (bug reports/feature requests/discussion/patches) are welcome.

**Comment by ironbishop** [comment]
We'll list Bookie instead of Shaarli. If it's still active, see #116 .

**Comment by ArthurHoaro** [comment]
Hi, I don't know this project, but Shaarli has been in active development for the past few years, and don't officially provide a hosted instance.
