### ISSUE TITLE
Add Converse.js (XMPP/Jabber chat client)

### ISSUE THREAD

**Issue by GreenLunar** [libreprojects/libreprojects#118]
Converse.js enables you to add chat functionality to your website, independent of any specific backend.

https://github.com/jcbrand/converse.js
https://conversejs.org/

**Comment by jancborchardt** [comment]
This is a developer-facing library rather than an app for users. So this doesn’t fully fit the criteria for Libre Projects. Thank you very much for the suggestion, but sorry. :)

**Comment by GreenLunar** [comment]
This is a high quality and great independent FB-chat-like for independent websites, it has MUC chats enabled and has OTR encryption.  It is far better than Jappix Mini.

@jcbrand please join to this discussion.

**Comment by jcbrand** [comment]
Hi @GreenLunar, thanks for spreading the word about converse.js :)

Hi @jancborchardt, converse.js is not a library, it's an application.

Looking at your criteria:

> open-source downloadable free software

Check.

> web-based & hosted and with a gratis plan

Check. Hosted on https://conversejs.org and can easily be hosted out of the box yourself.

> usable easy to use for everyone

This is more subjective, but it's used daily by people from all over the world, including many people without technical experience.

In any case, I leave it up to you to decide. If you still don't want to include it, that's your prerogative.

**Comment by jancborchardt** [comment]
@jcbrand ok, thank you for the info. :) Nevertheless I would say it’s a bit strange for normal people since it’s not a standalone application. If I use it on conversejs.org then I am basically on a site explaning stuff to developers.

If you have a standalone instance of that which looks like a regular chat app then please let us know again. :)

**Comment by jcbrand** [comment]
@jancborchardt Well, it IS a standalone application. If you go to https://conversejs.org, you can use it immediately. You can register a new XMPP account, log in and just start chatting. No developer skills required.

You can also host the website yourself, exactly as you see it in https://conversejs.org.

There are two usecases for converse.js:
- Using it as a standalone, web-based XMPP client (like on https://conversejs.org )
- Using it as an extensible/customizable application that can be integrated into other websites (i.e. more like a library for developers).

I think you are being put off by the fact that the text of the website focuses more on the 2nd usecase.

Fair enough. I'll think about how I can make it more clear to people that they can use converse.js as a standalone application.

For example, I think it's a great way for people to register new XMPP accounts. You can register an account on any public XMPP server. I'm not aware of any other website which enables you to do this. Besides that, you can use it as a web-based chat client whenever you don't have a native chat client available. It's also great for bypassing corporate firewalls :)

**Comment by GreenLunar** [comment]
Bump!

https://github.com/candy-chat/candy/stargazers (over 1200 stars)
https://github.com/jappix/jappix/stargazers (below 400 stars)

**Comment by GreenLunar** [comment]
Notice the differences!

https://github.com/candy-chat/candy/stargazers (over 1200 stars)
https://github.com/jappix/jappix/stargazers (below 400 stars)

**Comment by jancborchardt** [comment]
@GreenLunar bump what? Candy chat does not have a running instance for people to use, which is a requirement to be added to Libre Projects. Also, stargazers are not a fully meaningful metric.

**Comment by GreenLunar** [comment]
> stargazers are not a fully meaningful metric

I disagree to this statement.  Most of XMPP developers and programmers use Gajim or Psi as their desktop clients, unfortunately, in concern to Gajim which has poor to non marketing plans, is not popular amongst most end-users.  Having GitHub users staring candy more so than Jappix gives a heavy indication of what Candy worth and what potential it has.
