### ISSUE TITLE
Add Candy (XMPP/Jabber multi-user chat client)

### ISSUE THREAD

**Issue by GreenLunar** [libreprojects/libreprojects#119]
Candy — abbreviation for Chats are not dead yet — is a JavaScript-based multi-user chat client for XMPP.

https://github.com/candy-chat/candy
http://candy-chat.github.io/candy/

**Comment by jancborchardt** [comment]
This doesn’t seem to have a hosted instance ready to use. Jappix does, and we have that already: http://libreprojects.net/#project=jappix

**Comment by GreenLunar** [comment]
Even though it is not as popular as Jappix or JWChat, it is different as it does not use PHP and is extensible with plugins.

@benlangfeld @melissanoelle @mweibel @pstadler

Is there a list of public Candy Chat instances?

**Comment by GreenLunar** [comment]
@benlangfeld @melissanoelle @mweibel @pstadler

Is there a list of public Candy Chat instances?

**Comment by GreenLunar** [comment]
@benlangfeld @melissanoelle @mweibel @pstadler

Is there a list of public Candy Chat instances?

**Comment by mweibel** [comment]
Hi,

except our demo, I don't think there's anyone hosting it publicly.
Not sure what requirements libreprojects has, could you elaborate?

**Comment by airon90** [comment]
@mweibel:

From [README.md](https://github.com/libreprojects/libreprojects/blob/gh-pages/README.md):

```
- open-source downloadable free software
- web-based & hosted and with a gratis plan
- usable easy to use for everyone
```

**Comment by GreenLunar** [comment]
> I don't think there's anyone hosting it publicly.

Ta! Da! http://candy.linkmauve.fr/#touhou@muc.linkmauve.fr

**Comment by GreenLunar** [comment]
I am about to remove my last comment, because the above instance is restricted to the server in which it is hosted.

**Comment by GreenLunar** [comment]
To whom it may concern:

> You could use bind.chatme.im or bind.jappix.com for an open BOSH service. And host Candy wherever you want.

By Link Mauve
From http://candy.linkmauve.fr/#touhou@muc.linkmauve.fr (restricted Candy Chat instance)

**Comment by GreenLunar** [comment]
Bump!

By the way, Jappix is dwarfing in the presence of Candy Chat, especially in security.

https://github.com/candy-chat/candy/stargazers (over 1100 stars)
https://github.com/jappix/jappix/stargazers (below 400 stars)

Servers running Candy Chat
https://github.com/candy-chat/candy/wiki/Candy-Instances
https://github.com/candy-chat/candy/wiki/Candy-In-The-Wild

**Comment by GreenLunar** [comment]
By the way, Jappix is dwarfing in the presence of Candy Chat.

**Comment by GreenLunar** [comment]
Notice the differences!

https://github.com/candy-chat/candy/stargazers (over 1100 stars)
https://github.com/jappix/jappix/stargazers (below 400 stars)

**Comment by GreenLunar** [comment]
Servers running Candy Chat
http://candy.linkmauve.fr/#touhou@muc.linkmauve.fr
http://chat.itunix.eu/
https://kraut.space/chat/
https://osgconnect.net/candy/
https://jabberpl.org/muc/chat/
http://www.shaxball.com/chat.html
http://www.codigosur.org/media/chat.html
http://ned1.myflorida.com/candy/

**Comment by GreenLunar** [comment]
@mweibel 
> except our demo, I don't think there's anyone hosting it publicly.

See https://github.com/candy-chat/candy/wiki/Candy-Instances
