### ISSUE TITLE
Add Speeqe (multi-user chat application over XMPP)

### ISSUE THREAD

**Issue by GreenLunar** [libreprojects/libreprojects#120]
It is not as fancy as Candy #119, but it is fast, minimal, reliable and straightforward. Speeqe needs new contributors to revive it.

Project https://github.com/thepug/Speeqe
See it in action at http://chat.ownclub.net/

**Comment by jancborchardt** [comment]
The SSL certificate doesn’t seem to work there anymore. Really seems more like just a demo, and as mentioned in another issue we already have Jappix: http://libreprojects.net/#project=jappix

(Sorry – but Libre Projects is focused on showing actually usable, hosted web apps. :)

**Comment by GreenLunar** [comment]
It is a great XMPP MUC chat software. It is simple, lightweight and fun.

Speeqe (Python based) needs enthusiastic developers.
