### ISSUE TITLE
Ikiwiki (wiki compiler)

### ISSUE THREAD

**Issue by GreenLunar** [libreprojects/libreprojects#121]
May be used for [blogging](http://ikiwiki.info/blog/) and [podcasting](http://ikiwiki.info/podcast/), as well as a large array of [plugins](http://ikiwiki.info/plugins/),

Homepage: http://ikiwiki.info/

**Comment by ironbishop** [comment]
Doesn't have a hosted instance, and we already list the Wikimedia prokects.

It's not suitable for LibreProjects.
