### ISSUE TITLE
firepad

### ISSUE THREAD

**Issue by zhr0** [libreprojects/libreprojects#122]
http://www.firepad.io/

**Comment by GreenLunar** [comment]
Open source collaborative code and text editing

This is a nice project. Thank you for sharing.

**Comment by jancborchardt** [comment]
It seems to be just a copy of the _truly_ open source [Etherpad](http://etherpad.org/), but on top of the proprietary [Firebase](https://www.firebase.com/) service.
(Etherpad we already list, in the form of [Titanpad](https://titanpad.com/).)

Thanks for the suggestion, but no.
