### ISSUE TITLE
project suggestion: inventaire.io

### ISSUE THREAD

**Issue by maxlath** [libreprojects/libreprojects#126]
(its my own project)
[inventaire.io](https://inventaire.io/) is a libre resources mapper powered by open knowledge, which in its first version translate into keeping the inventory of your books using wikidata

repo: [github.com/maxlath/inventaire](http://github.com/maxlath/inventaire)
licence: AGPL3

background motivations are sketched on the [home page](https://inventaire.io/welcome), but if you are interested in digging further, I would recommend you the article I wrote a while ago on [p2p-rm](http://maxlath.eu/p2p-rm)

[![inventory-georges](http://profile.maxlath.eu/slides/backbone-meetup/img/inventory-georges.png)](https://inventaire.io)

**Comment by jancborchardt** [comment]
@maxlath looks nice and seems to fit well! Can you add it as described in the readme: https://github.com/libreprojects/libreprojects#adding-new-projects – probably best in the »Text« category. :)

**Comment by emjayess** [comment]
really cool project!

**Comment by maxlath** [comment]
thanks :D If you try it, I'm very much looking forward for your feedbacks! :)
PR: #127

**Comment by ironbishop** [comment]
merged
