### ISSUE TITLE
Add Taiga as an open source project

### ISSUE THREAD

**Issue by Xaviju** [libreprojects/libreprojects#128]
https://taiga.io/
https://github.com/taigaio

**Comment by jancborchardt** [comment]
Please just directly add it – it’s very simple as described in the readme: https://github.com/libreprojects/libreprojects#adding-new-projects :)

**Comment by jancborchardt** [comment]
Btw first impression: Looks sleek as hell, good job! But the performance _really_ needs to step up, there’s way too many and long loading phases (the big white »Loading …« overlay is also too present).

**Comment by Xaviju** [comment]
Sorry @jancborchardt I'll do it.
About the performance, we are still working on how to make users experience better on this area and of course reduce loading times. I would love to kill that loading screen (hate it!) but still did not have time to figure out and develop a better way. 
Thanks for your kind words!

**Comment by jancborchardt** [comment]
Added via https://github.com/libreprojects/libreprojects/pull/129 – thanks for the submission! :)
