### ISSUE TITLE
"scroll" parameter to link directly to category does not work

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#130]
Try to open http://libreprojects.net/#scroll=organization (as tweeted by @xaviju at https://twitter.com/Xaviju/status/617980379920793600 )

And it will change to override with the default favs anchor like so: http://libreprojects.net/#favs=joindiaspora-com,owncloud,openstreetmap,jamendo,cloud9,plos

Instead, the favs anchor should be added but the scroll anchor kept as well. Any idea @libreprojects/contributors?

**Comment by ironbishop** [comment]
duplicate #70
