### ISSUE TITLE
Please replace Gitorious with GitLab

### ISSUE THREAD

**Issue by dosire** [libreprojects/libreprojects#131]
GitLab replaced Gitorious https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/
GitLab CE is MIT Expat licensed
New logo can be found in https://gitlab.com/gitlab-com/gitlab-artwork/tree/master.
Please let me know if you have any questions.

**Comment by dosire** [comment]
Best url to use is https://about.gitlab.com/

**Comment by jancborchardt** [comment]
Right, good call! Can you submit a pull request for it as described in https://github.com/libreprojects/libreprojects#adding-new-projects ? That’s best so everything is as you want it. Thanks!

**Comment by dosire** [comment]
Closed with https://github.com/libreprojects/libreprojects/pull/132

**Comment by jancborchardt** [comment]
@dosire @JobV thanks! I love Gitlab and would actually like to put some time into design help, but currently too much to do on ownCloud. :) Great job!

**Comment by dosire** [comment]
Thanks @jancborchardt

**Comment by yuwash** [comment]
I’m reacting a bit late, but it seems that the site Gitlab.com doesn’t offer a gratis plan, if I’m not missing anything?

**Comment by dosire** [comment]
@yuwash You can use GitLab.com for free https://about.gitlab.com/gitlab-com/ (only email support is paid)

**Comment by jancborchardt** [comment]
Yup, it’s also very present as the right item on https://about.gitlab.com/

**Comment by yuwash** [comment]
Thanks for the clarification of the obvious. Indeed it seems I was somehow blind :smiley: (not seeing any price or “free” in **big letters**, I directly moved to the “pricing” page)

**Comment by dosire** [comment]
@yuwash Yeah, pricing page is for EE only, it does have "Sign up for our free GitLab.com service if you want to use GitLab without installing it." but that is down on the page.
