### ISSUE TITLE
universeOS

### ISSUE THREAD

**Issue by niczem** [libreprojects/libreprojects#137]
Hey there,

we are developing the universeOS a PHP and JS based webDesktop. Maybe you like it :)

**Comment by jancborchardt** [comment]
It looks a lot like [Nextcloud](https://nextcloud.com), except with additional windows inside of an already existing browser window. ;) And Nextcloud is also open source and already quite established: https://github.com/nextcloud/server

I’m always a bit wary of these web-based »desktop« replacements. I don’t think the typical desktop is a particularly good metaphor design-wise, as we can see from the development of way simpler mobile operating systems. Also it’s a lot of work to do all the windowing stuff, and it introduces a big potential for bugs.

**Comment by jancborchardt** [comment]
This is not meant as demotivating, just as a hint of how complicted it is to build such a system. Nextcloud also has apps like Calendar, Contacts, Music player etc and even with lots more people than you there’s a struggle already. It’s very difficult properly developing all this into a product and maintaining it.

**Comment by niczem** [comment]
Thanks for the comment. Nextcloud is way more accomplished. I am happy, that the whole thing is running quite stable right now :)

We adapted the known system of draggable applications to give the possibility to drag and drop items from one application to another but we are planing a "single application layout" for mobile devices.

And yeah it is complicated to build such a system and there is still a lot to be done, but I hope we are on a good way. Thank you very much for those comments so far :)
