### ISSUE TITLE
default favorites

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#14]
Partly to advertise the favorites function, but also to simply showcase the best projects on the site which might be far down, there should be some default favorites.

What about: http://libreprojects.net/#favs=diaspora,owncloud,youtify,newsblur,openstreetmap,etherpad,mediagoblin,cloud9

These projects are all relevant and useful for many people (I use each almost daily), they are in active development and have a good community. I intentionally left out big projects such as Wikipedia, Reddit and Wordpress because they don’t need more advertisement.

Does that sound good? What do you think @jhuet? Also, how can we integrate that so that only people with no favorites yet get those added? Or maybe we should actually just do it for everyone – just add these projects on top of their existing favorites, regardless if they have none or some.

**Comment by jhuet** [comment]
I like the idea of having by default favorite apps. I'm not sure about having them on top of the user's ones though. It sounds too much like "Featured app" we could see on some ads :) the worse being that the user couldn't remove them.

I guess we could use some kind of flag to check if the user ever tried to fav or unfav something thus we wouldn't add these default fav apps anymore.

**Comment by jancborchardt** [comment]
Yeah, I totally agree with you! I didn’t mean to add them as permanent featured apps – just add it to the current favorites. It’s a one-time action, so if people unfavorite some or all of them again it will not add them again.

I do realize now however this would be somehow hard to check. Let’s maybe just do that for instances where the user has no favorites at all – because it’s likely that they just visit for the first time, or don’t know about the favorites function.

**Comment by jhuet** [comment]
With localStorage we could add a flag `displayDefaultApp = true` and put it as `false` if the user ever add or remove an app. Then we would never add those apps anymore. I guess that'd work, i'll try it out.

**Comment by jhuet** [comment]
It will reset all already used favs but don't think it's much of a problem as it wasn't used much right now. Will have to pay more attention as of now as the goal of that improvement is to make it more popular.

**Comment by jancborchardt** [comment]
Nice! Good call on the service choice also.
