### ISSUE TITLE
reddit logo missing

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#140]
Can you reproduce this @libreprojects/contributors? The reddit logo is missing for me on http://libreprojects.net/ (Social category, should be second entry)

**Comment by airon90** [comment]
Using latest Firefox Nightly on Arch Linux

![schermata 2015-11-13 alle 20 21 50](https://cloud.githubusercontent.com/assets/139841/11155153/25143392-8a44-11e5-8285-8b71747c1923.png)

**Comment by jancborchardt** [comment]
Ah, I guess it’s because of the adblocker :D Might block every image called »reddit.png«, just as it does for share.png etc.
