### ISSUE TITLE
Open Source Routing Machine

### ISSUE THREAD

**Issue by Anth0rx** [libreprojects/libreprojects#148]
The [Open Source Routing Machine (OSRM)](http://project-osrm.org/) is a "[m]odern C++ routing engine for shortest paths in road networks." It is available under the "Simplified BSD License" and hence should be added to the list.

**Comment by ironbishop** [comment]
What are the diffrences between OSRM and Graphhopper, that's already in the list?

**Comment by jancborchardt** [comment]
Actually, since https://www.openstreetmap.org now has routing built-in, that’s the most usable platform for maps & routing. I’ll remove Graphhopper then. :)
