### ISSUE TITLE
You should add gogs.io under the development section

### ISSUE THREAD

**Issue by deavmi** [libreprojects/libreprojects#151]
You should add gogs.io under the development section.

**Comment by jancborchardt** [comment]
How does this compare to [Gitlab](https://about.gitlab.com/), which seems like the most mature project in this area?

As mentioned in the [Libre Projects readme](https://github.com/libreprojects/libreprojects#libre-projects) :)
> Not every project will be listed here, especially not complicated ones. It’s not about giving many choices, it’s about providing the best solutions.

**Comment by deavmi** [comment]
Gogs is pretty mature as well.

**Comment by deavmi** [comment]
Gogs is a pretty good solution though. Well, you can make up your mind 
on which one is the best. I just wanted to let you k now :smile:

**Comment by jancborchardt** [comment]
@deavmi yeah, thanks for that, it’s always cool to see new projects. :) With Libre Projects however we already have a bunch and we want to focus on showcasing the absolute best – as there are many general lists, for example on Wikipedia. :)

**Comment by deavmi** [comment]
Ok. That's cool. I guess then GitLab is the winner.

**Comment by deavmi** [comment]
In this situation.
