### ISSUE TITLE
Permadelete

### ISSUE THREAD

**Issue by mhmd-azeez** [libreprojects/libreprojects#152]
[Permadelete](https://encrypt0r.github.io/permadelete/) is a free and open source file shredder for Windows. And [here](https://github.com/encrypt0r/permadelete) is the project repo.

![Screenshot](https://github.com/encrypt0r/permadelete/raw/master/screenshots/mainwindow.png)

**Comment by lucab** [comment]
This seems to be a Windows application, while here we collect
> open source hosted web services

**Comment by mhmd-azeez** [comment]
@lucab  Sorry, I thought you collect software too. 

> open-source downloadable free software

One question: Does it matter if it's a Windows app or some other Systems app?

**Comment by lucab** [comment]
No, it doesn't matter. This repo only collects hosted FLOSS web services.
