### ISSUE TITLE
wire instead of echoplex

### ISSUE THREAD

**Issue by ironbishop** [libreprojects/libreprojects#157]
Echoplexus has been discontinued. (Mar 18, 2016)
It still works (I presume, still have to check). 

Should we list Wire instead? @libreprojects/contributors, what do you think?
Free as in Freedom :white_check_mark: 
Web-based & Hosted :white_check_mark: 

https://wire.com/
https://github.com/wireapp

**Comment by jancborchardt** [comment]
Wire is not yet fully open source, unfortunately:

https://github.com/wireapp/wire-server#wire-server

> This repository contains the source code for the Wire server. **At the moment it contains a subset of the libraries and services used by Wire.** We will keep releasing more libraries and services over time as we finish cleaning up and documenting the source code. Our goal is to publish the source code of the entire Wire server.

**Comment by jancborchardt** [comment]
But yes, echoplexus should be removed independent of that. :)

**Comment by yuwash** [comment]
That’s unfortunate. ~~The only opensource web video chat I could find is [AppRTC](https://appr.tc/) which is very basic, though, hey, who really needs additional features…~~ [Jitsi Meet](https://meet.jit.si/) ([source repository](https://github.com/jitsi/jitsi-meet)) might be a viable alternative, though lacking a whiteboard, but featuring an Etherpad integration.

**Comment by jancborchardt** [comment]
Nextcloud also has voice & video chat :) https://nextcloud.com/webrtc/ - depending on the hoster of course.

So yeah, Jitsi meet is probably the most fitting. Want to add it to the site?
