### ISSUE TITLE
Orionhub.org is down

### ISSUE THREAD

**Issue by isupportlearning** [libreprojects/libreprojects#163]
I've had a few issues with Orionhub recently that are forcing me to reconsider using the tool. Over the last year it has been brilliant. Easy to use, effective and feature rich.

But over the last month or so, the platform has had an increasing amount of downtime. I'm writing courses, that use Orionhub.org as students main editor of choice. But I'm worried and very much considering swapping them over to cloud9 instead. We simply can't promote a site that's unstable.

I love orionhub.org and have been using it as my personal cloud development tool for years. But the recent increase of downtime has me extremely concerned about it's long and short term viability. Can anyone shed any light on this?

**Comment by jancborchardt** [comment]
Could you contact the people running the Orionhub platform for more information? :)

**Comment by ironbishop** [comment]
It's back online.
