### ISSUE TITLE
Add the project www.hubx.io

### ISSUE THREAD

**Issue by HubXio** [libreprojects/libreprojects#166]
Hello Libreproject team,

i would like to add our project www.hubx.io to your register. An easy and free cryptocurrency compare for assets. Please write me for details.

Best wishes, Janos

**Comment by airon90** [comment]
Hi,
does your project satisfy these [requests](https://github.com/libreprojects/libreprojects/blob/gh-pages/README.md)?

- [ ] open-source downloadable free software
- [x] web-based
- [x] hosted
- [ ] with a gratis plan
- [x] usable easy to use for everyone

So we just need 
1. Is the source code available somewhere?
2. Will your project offer the service for free forever?

And remember: Not every project will be listed here, especially not complicated ones. It’s not about giving many choices, it’s about providing the best solutions.

**Comment by jancborchardt** [comment]
It doesn't seem open source, nor a real app besides currency comparison? Sorry but it doesn't fit what we want to showcase.
