### ISSUE TITLE
Take Reddit out

### ISSUE THREAD

**Issue by hhassey** [libreprojects/libreprojects#167]
I believe Reddit is no longer open source, so shouldn't be on the list!!

**Comment by ironbishop** [comment]
Ouch. Yep that's true.
https://www.reddit.com/r/changelog/comments/6xfyfg/an_update_on_the_state_of_the_redditreddit_and/

**Comment by ironbishop** [comment]
Should we add another project, while we remove this? (Does a free alternative exists?)

**Comment by hhassey** [comment]
Yes, I found VOAT https://voat.co its code is in Github.

And there was a massive amounts of people that migrated, me included, when
reddit closed its code.

HAve a good day!

**Comment by emjayess** [comment]
> Ouch. Yep that's true.
https://www.reddit.com/r/changelog/comments/6xfyfg/an_update_on_the_state_of_the_redditreddit_and/

Lol, _"which are playing an increasingly small role..."_

If only there was some other word for effectively conveying _"increasingly small"_.

**Comment by jancborchardt** [comment]
Yes, unfortunately Reddit went closed-source. Thanks @hhassey for bringing it up and @ironbishop for removing it.

A word on the proposed alternative "Voat": If you check their frontpage, it becomes very clear that under the guise of being "censorship-free" they are filled with people who are quite openly racist, sexist, anti-semite, "identitarian" (nationalist) and more. We **do not** support stuff like that with Libre Projects at all, and hence will _not_ add Voat.

**Comment by hhassey** [comment]
Totally agree with you on Voat!!
