### ISSUE TITLE
Gibberfish

### ISSUE THREAD

**Issue by rev138** [libreprojects/libreprojects#168]
https://gibberfish.org

Submitted for your approval. 

We are hosted, and free in all respects. However, we cater to specific groups and not the general public so I'm not sure if that qualifies.

**Comment by ironbishop** [comment]
Looks promising.

We already list 
* Nextcloud, which lacks conferencing (afaik)
* Jitsi Meet, which lacks calendar (afaik)

What are other main differences between these projects?
I also don't find the hosted part, is that still in beta?

**Comment by airon90** [comment]
Nextcloud has [Spreed](https://apps.nextcloud.com/apps/spreed) but I don't know if it is the same of Gibberfish

**Comment by rev138** [comment]
Spreed is one of their core apps.

**Comment by jancborchardt** [comment]
(Full disclosure: I'm Design Lead at Nextcloud.)

Looking at the screenshots Gibberfish looks like a hosted Nextcloud. It has Files and Calendar from Nextcloud, Collabora Online (which is also integrated in Nextcloud) and Spreed video calls which is not developed anymore in favor of Nextcloud Talk: https://github.com/nextcloud/spreed (also see talk-android and talk-ios :)

@rev138 Hence I'd say Gibberfish is rather more fitting to be listed as Nextcloud provider at https://nextcloud.com/providers, cc @jospoortvliet

**Comment by rev138** [comment]
Correct. Also, since those screenshots were taken we've switched over to "Talk".

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by jancborchardt** [comment]
Awesome @rev138 :) so could you contact @jospoortvliet to get added to the provider list there? :)

I'm closing this issue here then.
