### ISSUE TITLE
libertree

### ISSUE THREAD

**Issue by peacenik** [libreprojects/libreprojects#17]
Libertree is free, libre, open-source software which is intended to provide a way for people to create their own social network. Libertree social networks can be free from commercial influence and manifestation, such as behaviour tracking, user profiling, advertising, data mining and analysis, and covert information filtering.

The Libertree Project is a community of people committed to empowering the people of the world to do things on and with computers, without need for or interference from big business, by way of providing software and other tools which can be obtained, bought or built with minimal cost and effort. 
(quoted from the website for ["The Libertree Project"](http://libertreeproject.org/)

suggested [data.json](https://github.com/libreprojects/libreprojects/blob/gh-pages/js/data.json) entry:
{"id":"libertree","category":"social","name":"Libertree","description":"social multi network","address":"http:\/\/libertreeproject.org\/","licenses":["GNU Affero"],"tags ["social","network","decentralized","microblog"],"alternative":["facebook","google plus","twitter","friendica"]}

**Comment by Pistos** [comment]
It's not really a "social multi network", just a "social network".  Licence is AGPL3.

**Comment by jancborchardt** [comment]
Hey! Thanks for the suggestion. Libertree seems to be in a very early stage though, unlike similar open source social networks Diaspora and Friendica. Libre Projects is focused on very easily usable services and, in the case of a social network, used by a reasonable number of people.

For the same reason, other open source social networks like Crabgrass, Buddycloud, Elgg, and others are not on Libre Projects. I put Libertree on the list in #10, and we’ll reconsider once it’s in a more mature state.

Remember Libre Projects is focused on showcasing web services for the common user and not developers – there are plenty of other lists for that.
