### ISSUE TITLE
Drupal - correcting site & logo references

### ISSUE THREAD

**Issue by emjayess** [libreprojects/libreprojects#173]
Under **Publishing**, the _Drupal_ project links to – and uses a logo from – a now obsolete commercially hosted Drupal-as-a-service offering, then known as _Drupal Gardens_, and once hosted by Acquia (Drupal's flagship commercial entity, founded by Drupal project founder Dries Buytaert; but hardly the only entity offering commercial Drupal hosting services):

> ![drupal-gardens-incorrect](https://user-images.githubusercontent.com/194904/35239184-61a3015a-ff75-11e7-95ae-a727b9819915.png)

I'll submit a change/PR that updates the reference site/url to the project's _forever_ home, [Drupal.org](https://www.drupal.org/), alongside replacing the Drupal Gardens logo (which was only ever a logo for Acquia's commercial service, and is/was not the trademark logo for Drupal itself) with [Drupal's "druplicon" logo, from their official media kit](https://www.drupal.org/about/media-kit/logos):

> ![drupal-druplicon-correct](https://user-images.githubusercontent.com/194904/35239328-d3fb296c-ff75-11e7-978c-9c83df948fe2.png)

**Comment by jancborchardt** [comment]
Fixed through #174, thank you for the pull request @emjayess  :)
