### ISSUE TITLE
Add notice to allow Javascript for NoScript users

### ISSUE THREAD

**Issue by hex-m** [libreprojects/libreprojects#175]
If you access the page without enabling javascript you only see the "Information" and "Participate" paragraphs. It would be nice if it would at least show a message that tells the user to allow JS. Even better if it shows the content of course.

**Comment by jancborchardt** [comment]
Yeah, a notice to allow JS would be good. Do you want to contribute that @hex-m? :) cc @libreprojects/contributors

Showing the content is not possible as we load that via JS and the database and translations are in JSON.

**Comment by emjayess** [comment]
Oofduh. Not to be a pest, but what's the rationale for js-rendering of such a straightforward directory page?

**Comment by hex-m** [comment]
@jancborchardt: thanks for the invitation. :) I'm far from being a web-developer but I guess this can be solved with some research and copy-pasting. Don't hold your breath but I'll look into it.

**Comment by jancborchardt** [comment]
@emjayess we use Github pages as hosting so it’s all fully clientside. We do not have a server-side database. We also do translations.

**Comment by hex-m** [comment]
It is merged and already live.
♥ Thanks to everyone involved! ♥

**Comment by jancborchardt** [comment]
Thanks especially to @Ramear225 for implementing it! :)
