### ISSUE TITLE
HTTPS does not work

### ISSUE THREAD

**Issue by rameardo** [libreprojects/libreprojects#180]
Hallo,
i have tried to browse libreprojects.net with HTTPS but it is not working.
When I browse the Website I see a message saying that there is something wrong with the server.

Thank you for this project.

Regards.

**Comment by jancborchardt** [comment]
Good catch, have now updated it according to the HTTPS guide for domains on Github pages: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by jancborchardt** [comment]
This is now live at https://libreprojects.net ! :) Check it out @libreprojects/contributors, we now have HTTPS! :tada: :lock:
