### ISSUE TITLE
Suggestion to add CodiMD to the List

### ISSUE THREAD

**Issue by ccoenen** [libreprojects/libreprojects#188]
CodiMD is a collaborative MarkDown editor, it works somewhat like Hackpad or Etherpad (lite). It is related to HackMD, but it's the AGPL fork of it.
Here's the repository: https://github.com/codimd/server
And here's the demo-installation that lets you try it out without installing it yourself: https://demo.codimd.org/

**Comment by ironbishop** [comment]
Since we still list Titanpad, that went down two years ago (and others, actually #182), this is a wonderful news!
Can you please remove Titanpad in the same PR? Thanks.

**Comment by ccoenen** [comment]
I felt a little weird removing someone else's project. But as it has been confirmed discontinued, I think this is a good idea.

**Comment by ironbishop** [comment]
looks good to merge, anyone else @libreprojects/contributors  ?

**Comment by lucab** [comment]
That's also fine for me. Either in a single PR or in multiple ones, just keep the commits split apart.

**Comment by jancborchardt** [comment]
Merged via https://github.com/libreprojects/libreprojects/pull/189, so closing this. :) Thanks a lot for your contribution @ccoenen!
