### ISSUE TITLE
Fronty.com

### ISSUE THREAD

**Issue by karen-gallienne** [libreprojects/libreprojects#194]
Image to HTML CSS converter powered by AI which builds websites in just a few minutes.
![fronty-logo (1)](https://user-images.githubusercontent.com/58722633/70997906-7460e080-20ef-11ea-852d-64d696195f01.jpg)

**Comment by ccoenen** [comment]
From what I can tell, this is not free/libre software (the source code is not available, and I can't tell if it's under any applicable license.). So far, this only looks like a service that's offered at no cost at the moment. Their FAQ states that shis is bound to change at some point.

If I missed anything, please let me know!
