### ISSUE TITLE
Add todolist desktop app

### ISSUE THREAD

**Issue by blaadje** [libreprojects/libreprojects#195]
Hello,
I'd like to add my project http://todo-list.io/

- [x] open-source downloadable free software
- [x] web-based & hosted and with a gratis plan
- [x] usable easy to use for everyone

Available for mac/windows/linux

Let me know if possible 😇 

---

<img  width="100%" alt="Screen Shot 2020-05-27 at 18 01 04" src="https://user-images.githubusercontent.com/24897042/83048671-4393b880-a04a-11ea-948f-7e447127f67f.png">

**Comment by jancborchardt** [comment]
Heyhey :) So I only see this being a desktop app, not "web-based & hosted and with a gratis plan", what am I missing?
