### ISSUE TITLE
Product Suggestion

### ISSUE THREAD

**Issue by theabbie** [libreprojects/libreprojects#197]
# CryptoCRIT

<img src="https://theabbie.github.io/files/CryptoCRIT.png" alt="CryptoCRIT">

CryptoCRIT is an open-source Cryptocurrency project which facilitates a Cryptocurrency wallet for making payments. The associated Cryptocurrency is called CritCoin.

https://github.com/rgab1508/CryptoCRIT

**Comment by ccoenen** [comment]
Even though I don't know if this is even in the scope of this project I wanted to take a look at it. I was not able to find the source code. The Mentioned repository is just a readme and an empty compose.json file?

**Comment by theabbie** [comment]
@ccoenen We are ready with the prototype, And are actively working on it, It will be finished within few months, Can It still be added?

**Comment by ccoenen** [comment]
Well, it's not clear to me if this actually libre software (for which we would have to know the license). And without code being publicly available it wouldn't meet one of the most important criteria.

Ultimately it's not up to me to decide, but I would not be in favor of adding a project before one could even evaluate anything about it.

**Comment by theabbie** [comment]
@ccoenen It will be a Libre Software when ready, And code will be available publicly, And It is what's mentioned in the description, An open-source Cryptocurrency project, Actually, We are creating it as a college project, Should I apply when we are done with everything?

**Comment by ironbishop** [comment]
Your project is really cool, but... LibreProjects is about free (as in freedom) stable softwares, the excellence in their fields. Not prototypes. Also, LibreProjects is about software "easy to use for everyone". Cryptocurrencies are not mainstream enough to fall in this definition.

Instead, I just noticed we don't list any wallet. We should look into that, without focusing on a single currency. Maybe starting at https://opensource.com/article/18/7/crypto-wallets . Do you know any wallet that falls in the scope of our project?

**Comment by theabbie** [comment]
@ironbishop It's extremely Easy to Use, And Cryptocurrencies Being an emerging field, Even If it is not in your scope You could extend it, I have no Idea of any wallet in your scope, But, If you consider extending scope, there are a lot of possibilities

**Comment by ccoenen** [comment]
For the moment, the project does not meet the criteria *yet*. Front and center in the readme it states that it must be open source (which this project is not *yet*), web-based and hosted (both of which I can't verify at the moment), usable (which is somewhat subjective, but would also need at least a mostly complete MVP to test this).

So, as of right now, I would not accept this project. Feel absolutely free to reopen this at a later time. If anyone else from the team feels I'm overstepping by closing this, feel free to reopen as well.

All the best to you and your team!
