### ISSUE TITLE
remove protocol from links in database

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#20]
Currently, data.json has »http:\/\/« prepended to each web address.

Instead, all addresses should be without any protocol and without trailing slash – that can be added in the JS template.

**Comment by lucab** [comment]
I'm not really sure to support this intent, for two reasons:
- not everything will always be http. https anyone?
- current scheme makes data (directly from json) easily re-usable by anyone

On a related point: does they really need to be slash-escaped? licenses are not, and looks saner...

**Comment by jancborchardt** [comment]
Oh right, good point with the data reusability. @jhuet do you know if we can just not slash-escape?

**Comment by jhuet** [comment]
I tend to agree with @lucab. But anyway from what i [found around](http://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped), forward slashes don't necessarily have to be escaped. They are only necessary if they are used in `<script>` tag wich i don't think we do. If that is confirmed maybe we could just remove them.

**Comment by jancborchardt** [comment]
Yeah, I didn’t use slashes in the changes to the Games category, and neither for the Emulators. Replaced everything with simple forward-slashes now, seems to work.
