### ISSUE TITLE
web-based, free plan available, clients for multiple social platforms

### ISSUE THREAD

**Issue by ironbishop** [libreprojects/libreprojects#206]
Reddit client: https://github.com/libreddit/libreddit
YouTube client: https://github.com/iv-org/invidious
Twitter client: https://github.com/zedeus/nitter

License is AGPL-3.0 for all of them.

Would you approve these to be added, should i make a PR?

**Comment by ironbishop** [comment]
Adding: https://github.com/pablouser1/ProxiTok

**Comment by ironbishop** [comment]
ping @libreprojects/contributors

**Comment by jancborchardt** [comment]
Hi @ironbishop, sorry for the late reply. :)

So I would say no to all of them, as they are all non-free services, just with a different frontend. And that doesn't really change much in where the data lies.

The actual solutions are e.g.:
- Twitter → Mastodon
- Youtube → Peertube
- Instagram → Pixelfed
- and so on

Hope that makes sense? :)

**Comment by ironbishop** [comment]
yes, thank you
