### ISSUE TITLE
Suggested OSS: It is called It's FOSS (https://itsfoss.com)

### ISSUE THREAD

**Issue by MichaelTheGamer** [libreprojects/libreprojects#208]
Hello!   

   My friend Abhishek has a couple of sites that I really think at least one of them which I listed above could really potentially be a candidate. I am telling you what you could already find out for yourself and limiting it to that for now because I have sent him a note that is basically telling about you guys and the FLOSS that is so good for everyone! lol   
   Anyway, they do have _both_ free and paid memberships, newsletters, and while is hugely aimed at Linux/Unix PCs and servers, they do have a few Windows and Mac-aimed news (though I think it just defaults to working that way and they are including them kinda by proxy, if you get my meaning) and many other resources. It is quite diverse and informative as well as very up to date! I will be in touch either way. Thanks! 

Michael Carcieri

**Comment by ccoenen** [comment]
Hi!

Thank you for bringing this to his attention! If he wants to add any specific project to this list, that's a very welcome addition.

itsfoss.com itself does not fall under this project's criteria, I'm afraid. It's not a software itself, it can't be self-hosted as far as I'm aware? (well, the underlying Ghost can be self-hosted, but that's not the point).

Feel free to re-open this if I'm missing the point :-)
