### ISSUE TITLE
URL coding team

### ISSUE THREAD

**Issue by Blubberland** [libreprojects/libreprojects#211]
I'm pretty sure, there's something wrong.
Maybe check the URL for coding team.
Not sure if someone took over that site or you just got the wrong URL, but this site looks like a website for indonesian rooster fights (which is distusting).
![Screenshot from 2024-04-30 01-02-25](https://github.com/libreprojects/libreprojects/assets/109285352/437c72df-a28b-4f81-a95f-330ba47f78f4)

Didn't know how else to contact. Sorry.

Might this be the correct URL?
https://codingteam.erwanbriand.fr/

**Comment by Blubberland** [comment]
You're listing a lot of dead projects there.
Codingteam seems to be one of them. (for 4 years)
And their website was taken over.

**Comment by ccoenen** [comment]
Good catch! I don't think anyone is monitoring the existing links. Personally, I only take a look at the (rare) new submissions. If you would like to contribute this in form of a pull request, the offending line would be this here: 

https://github.com/libreprojects/libreprojects/blob/7df4f93aaec22ac92f9b1d8b7e1f5981445e75fd/js/data.json#L145

But even if you don't want to contribute this in form of code, I'd like to say thank you for bringing it up!

**Comment by ironbishop** [comment]
on the same page, should we keep freenode? was taken over too

**Comment by jancborchardt** [comment]
Good points, created a pull request to remove both Codingteam and Freenode at https://github.com/libreprojects/libreprojects/pull/212
