### ISSUE TITLE
Requesting indexing BengalBoot

### ISSUE THREAD

**Issue by BCW52** [libreprojects/libreprojects#213]
It was a misunderstanding, it's good as closed. I am going to use this issues to add my project future. Thanks for your help @ccoenen

**Comment by ccoenen** [comment]
Hi, this is not really what libreprojects is about. Also your link appears to lead nowhere, so I took the liberty of removing it. Feel free to add the link again once it is back in working order.

From your description, your project does not really fit our collection. We're about open source (this checks out) that is also available with a free hosted version of that software (this, I think, does not fit your project). If I missed anything, feel free to reopen this and I will take another look.
