### ISSUE TITLE
OrionHub

### ISSUE THREAD

**Issue by mmilinkov** [libreprojects/libreprojects#23]
I would like to suggest that you add orionhub.org, which is the hosted Orion offering maintained by the Eclipse Foundation. All of the code is under the EDL(BSD) or EPL licenses, which are OSI-certified FLOSS licenses.

Orion is a development tool. It offers an excellent multi-language editing tool and an extensible tools platform which runs in your browser.

Some links:
http://orionhub.org/
http://eclipse.org/orion/ 
http://eclipse.org/

**Comment by jhuet** [comment]
Thanks for your submission @mmilinkov !

Sounds good to me so far. We might wait for the 3rd of october though as they say : _Registrations are currently disabled. Please check back around October 3rd_. Nonetheless this will be a great addition on the side of cloud9 :)

**Comment by jancborchardt** [comment]
Nice! I looked at Orion a while ago and am excited what’s upcoming. As @jhuet said we’ll wait with adding though until registration is public.

**Comment by mmilinkov** [comment]
That makes good sense. October 3rd is not that far away!

Basically the team is going to set things up so you can register for orionhub right on orionhub without the annoying re-direct to eclipse.org. Goodness knows what we were smoking when we thought that was a good idea :)

**Comment by mmilinkov** [comment]
Looks like orionhub.org is ready for new business :)

**Comment by mmilinkov** [comment]
<sigh> Ignore that. Let's wait a little longer. Looks like there's not a lot of value in pointing people to the site until Oct. 18th or thereabouts. I will ping again then. Sorry!

2012/10/05 IMPORTANT: OrionHub Server Migration for 1.0 - your data is moving
We have re-enabled registrations directly from OrionHub and will accept new registrations until 1.0 BUT PLEASE NOTE that the existing orionhub.org server will be moved to a backup system [backup.orionhub.org] on or around October 18th,2012 and orionhub.org will start from a brand new state so you will be required to re-register. Some of the reasons centre around lack of consistency in usernames, emails and our move to supporting different login schemes (Persona for example). Your existing data will be available at the alternative site with your old username/password for a minimum of 3 months. For updates follow us on Twitter @orionhub.

**Comment by mmilinkov** [comment]
So, orionhub.org is ready to go! So please add Orion to your list. Thanks!

**Comment by jhuet** [comment]
I first tried to login with Persona and it told me my email address wasn't linked to an OrionHub account (duh lol) so i tried to create an account, i confirmed it with the link in the e-mail but then, when i click on the Sign-in button, nothing happens. Is it me or... ?

**Comment by jhuet** [comment]
Ok my bad, it's working but they're experiencing performance issues :)

**Comment by kenwalker** [comment]
Mike forwarded me your message, but I see you got connected.  Persona, yes requires you to have a matching valid email first in the OrionHub profile for your account.  Should be smooth sailing after that.

**Comment by jhuet** [comment]
Thanks @kenwalker, i thought login thru Persona would automatically create an account. But i'm not familiar with it at all so maybe i was thinking too much in an OpenID or OAuth way.

**Comment by mmilinkov** [comment]
Jérémy,

Just so you know, the Orion client is actually dual-licensed EPL+New BSD.
