### ISSUE TITLE
Ubuntu One

### ISSUE THREAD

**Issue by jhuet** [libreprojects/libreprojects#24]
When looking for data for the Tools category i wanted to find similar projects to ownCloud and ran into [Ubuntu One](one.ubuntu.com). I thought it could be a good addition here but found out that the code running on the server is [not opensource](http://en.wikipedia.org/wiki/Ubuntu_One) but the client's are.

Because of that, i finally put it as an alternative, but i wanted your input on this.

**Comment by lucab** [comment]
Ideally for me, a libreproject entry should fulfill these usecases:
- I can look at the sourcecode, contribute patch, debug...
- I can install and use my own instance on my server

While useful, Ubuntu One doesn't seem to fit. 

P.S. I know I'm probably biased toward http://wiki.debian.org/FreedomBox/LeavingTheCloud

**Comment by jancborchardt** [comment]
Yeah, totally right. Ubuntu One is not fully open source, so it only qualifies as being listed as »ownCloud being an alternative to it«.

@lucab the bias is completely ok. Though the additional requirements for Libre Projects are being easily usable (as purportedly subjective as this is) and also being hosted with a free (gratis) plan available, so anyone can easily use it. It’s not really libre if I need own server, or if it’s hard to use, or if I need to pay.
