### ISSUE TITLE
Fontsquirrel & Google web fonts

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#25]
Several times I have now thought about adding [Fontsquirrel](http://fontsquirrel.com),  a directory of fonts »100% free for commercial-use«. The license is often SIL Open Font License, but oftentimes also one thought up by the font author.

Similarly [Google web fonts](https://www.google.com/webfonts): There’s a bunch of open source fonts there, but I am a) not really comfortable with adding a Google service to the site and b) not sure if they are all 100% open source because the focus seems to be »use on the web«.

We already have the great [Open Font Library](http://openfontlibrary.org) and [The League of Movable Type](http://theleagueofmovabletype.com/) which are more committed to openness. Some open source fonts are not listed on those sites, while they are on Fontsquirrel or Google web fonts. I’m not sure though if we should include either of those as stated before. Mostly because then we would have 3 or more typography sites, and also because we could just get the missing typefaces added to Open Font Library instead.

What do you think? I’d also like your input, @davelab6

**Comment by davelab6** [comment]
Disclaimer: I work as a consultant to the Google Web Fonts project, and
this is my own personal opinion:

FontSquirrel has a lot of proprietary fonts!

Google Web Fonts contains only libre fonts! As policy! :)

You can link to http://code.google.com/p/googlefontdirectory/ if you just
want to point to the files and not the service.

**Comment by davelab6** [comment]
Although GWF seems to fit the
https://github.com/libreprojects/libreprojects/blob/gh-pages/README.md
description very well.

**Comment by jancborchardt** [comment]
Thank you for the feedback, especially for the info that FontSquirrel has a bunch of proprietary fonts, so that’s definitely out of scope.

@jhuet, @lucab what’s your stance on adding Google Web Fonts?

**Comment by jhuet** [comment]
Thanks @davelab6 for the complementary information. I can understand not really wanting to advertise Google services but honestly it wouldn't be very fair if that service fits into our policy to not add it. I personnaly wouldn't be against it.

**Comment by jancborchardt** [comment]
Agree, it’s just fair to add it. Done. Thank you @davelab6 and big up for your font freeing!

**Comment by lucab** [comment]
Sorry for coming late, but basically on the same line as @jhuet.

**Comment by jancborchardt** [comment]
Super!
