### ISSUE TITLE
OpenPhoto

### ISSUE THREAD

**Issue by jmathai** [libreprojects/libreprojects#26]
Hosted @ https://openphoto.me

Source @ http://github.com/photo

Information @ http://theopenphotoproject.org

**Comment by jhuet** [comment]
Thanks for your submission @jmathai ! It sounds good to me !

**Comment by jancborchardt** [comment]
Of course! Have been meaning to add OpenPhoto since some time (was already on #8 [projects to add]) and now it’s in! Thanks @jmathai for nudging (and for coding OpenPhoto).
