### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by lightonflux** [libreprojects/libreprojects#27]
It would be nice if there is an way to get informed about new projects.

**Comment by jhuet** [comment]
:+1: :)

**Comment by ironbishop** [comment]
can [this](https://github.com/libreprojects/libreprojects/commits/gh-pages.atom) be a starting point? :)

**Comment by jhuet** [comment]
I'm not sure the PRs are a good starting point. What would be best IMO, would be to create a RSS or ATOM feed that would be filled with the data from the `js/data.js` file. For example, we could add a new "addedDate" property for each project object. Then by listing them by reverse "addedDate" order we could create a feed containing the last ones added.

That said i'm not sure on how we could create such a feed directly by reading those data on the client-side.

**Comment by jancborchardt** [comment]
But for now, we could go with the simplest thing and add a meta tag for the RSS/ATOM in the HTML and refer the Github commit feed as @ironbishop mentioned. We shouldn’t add an RSS button on the site though because the feed is quite technical – but still this solution will enable people to subscribe to the site if they want to.

What do others think @libreprojects/contributors? Or does anyone want to do a pull request? :)

**Comment by ironbishop** [comment]
another option could be, maybe... building the RSS with a [post-receive](http://git-scm.com/book/en/Customizing-Git-Git-Hooks) hook

**Comment by ironbishop** [comment]
what would be better?
- A) manually build the feed when you need it (ie: ./feed.sh add 'title' 'content ....' ; git add feed/rss.xml ; commit, push, etc )
- B) hook: if data.json was modified, add the commit message to the feed and commit it
- C) hook: if commit message contains '[feed]', add the commit message to the feed (s/[feed]//) and commit it
- D) hook: if ./feed/\* was committed, add that file content to the feed (first line: item title; next: item content) and commit it

**Comment by jancborchardt** [comment]
Please check out https://github.com/libreprojects/libreprojects/pull/59 for a simple solution.
