### ISSUE TITLE
Tahoe-LAFS

### ISSUE THREAD

**Issue by zooko** [libreprojects/libreprojects#28]
I suggest you include a project I contribute to: Tahoe-LAFS. https://tahoe-lafs.org . It is open-source, hosted, and usable.

**Comment by jancborchardt** [comment]
Hey @zooko, good to see you on here! I met Lotharrr when I was in SF and we talked about Tahoe-LAFS, unhosted and remotestorage.

Tahoe-LAFS does not seem to be really hosted though. With »hosted« I mean that there needs to be a provider offering it so anyone can just sign up for an account and use it. Desktop software or downloads can’t be required. And also not »it’s hosted once you set it up on your own server« as many people can’t do that (that’s what the open source requirement is for – that if you know how to run it on your own server, you can also do it).

**Comment by zooko** [comment]
Oh, I see, good point! So, my startup company sells the server side of a Tahoe-LAFS grid. We sell "ciphertext storage service". But you still have to run the client-side yourself, so that it can do the encryption without our company having access to your encryption keys. Okay, thanks for explaining.

**Comment by jancborchardt** [comment]
Yeah, the focus of Libre Projects is readily hosted (with free plan available), very easily usable (regarding interface), open source web apps.
