### ISSUE TITLE
Openphoto and Pixlpaste

### ISSUE THREAD

**Issue by airon90** [libreprojects/libreprojects#30]
Openphoto should be deleted because you have to pay in order to host files.
I'd like to substitute it with [Pixlpaste](http://pixlpaste.com) ([source](https://github.com/alokmenghrajani/pixlpaste), AGPL), which permits to upload photos and to share them online

**Comment by alokmenghrajani** [comment]
like-stamp :)

Btw, i'm thinking about giving users the ability to save their data on their personal dropbox accounts. This way, if the service ever goes down, people will continue to own their data.

**Comment by jhuet** [comment]
Isn't Openphoto still free if you also use another data provider like DropBox ?

**Comment by jhuet** [comment]
Pixlepaste looks awesome, nice and easy ! I don't see why we shouldn't add it :)

**Comment by airon90** [comment]
I propose and I want to listen to comments from other persons.
I don't know how to add projects, too! I only look for new programs :)

Today I found Openphoto and I saw that you start a free 14-day trial, then you have to pay for sign up, which costs 45 $ every year. It seems that you pay for the service not only for the hosting [1].

[1] https://openphoto.me/signup

**Comment by jhuet** [comment]
And you're helping a lot @Airon90, thanks !

Okay i didn't know for OpenPhoto, i guess we're gonna have to remove it from LibreProjects then.

**Comment by jancborchardt** [comment]
Oh nice, Pixlpaste is useful and simple! It’s not quite the same as Openphoto – but we already have MediaGoblin anyway. :)

@jmathai Openphoto indeed seems to be impossible to use without cost, save for the 14-day-trial. Is that correct? We’ll remove it from Libre Projects then.

**Comment by jmathai** [comment]
@jancborchardt We only charge for the hosted/managed version of OpenPhoto. You're free to set it up yourself using any of our installation guides. http://theopenphotoproject.org/documentation

Unsure if that violates the policy for being listed on libre projects :)

**Comment by airon90** [comment]
We can leave it if only someone can find a site hosting Openphoto without paying for sign up, IMHO.

(Someone changed the site of MediaGoblin and now I found how it works.)

**Comment by jmathai** [comment]
PixlPaste is entirely different from OpenPhoto and MediaGoblin. I don't think it's a suitable replacement for either. It should be listed in addition.

MediaGoblin, however, is a suitable replacement for OpenPhoto if one of the requirements is that someone foots the hosting bill.

**Comment by jancborchardt** [comment]
Apparently https://openphoto.me has a free plan again, nice!

**Comment by jancborchardt** [comment]
@Airon90 you added Pixlpaste but apparently that was in the pull request we needed to revert because of incompatible changes. Can you open a new pull request, this time with individual smaller requests, like one for adding Pixlpaste? Thanks!

**Comment by airon90** [comment]
Sorry but I didn't have much free time. Can you update me? What should I have to do? Thank you!

**Comment by jancborchardt** [comment]
@Airon90 No worries! :) I’m not sure but I think you made one big pull request back then, and you or @jhuet reverted it because we accidentally merged it. That caused some good additions to be lost again. Can you do these changes again, this time in individual, smaller pull requests? :)

**Comment by airon90** [comment]
Is this issue valid yet?

**Comment by yuwash** [comment]
I made a simple new pull request (see above) just removing openphoto because it really needs to be removed anyway (it's redirecting to trovebox now). Pixlpaste.com is down now, so I can't check. Is it down for a longer period?

**Comment by jmathai** [comment]
Just a gripe that "free" in free and open source doesn't imply free of monetary charge.

We changed the name from OpenPhoto to Trovebox because of a legal copyright conflict. Everything is still _free_ly available under the MIT license at https://github.com/photo.

**Comment by jancborchardt** [comment]
@jmathai yeah, I know that, and I really appreciate that Trovebox is all still open source. The thing with Libre Projects though is that we have set ourselves some guidelines for what projects are included., like: open source, web app, nicely usable, hosted.

And one of them is that a hosted instance (or _the main_ hosted instance) should also offer a free plan (not just trial) – to ensure that also people without the means to pay for such a service can at least use a limited part of it.

I’m not asking you to offer up free-as-gratis plans, it’s just that we decided for a strict set of requirements for inclusion on Libre Projects. Hope that clarifies it.

And yeah, maybe we could re-evaluate that decision. Or add one or two additional categories: »No free plan available« and »No hosted instance«. Then again, that would fill up the list with lots of projects which are on other lists with different focus already.

**Comment by jmathai** [comment]
Jan, completely understand. I don't think you need to change anything or
add a section to the site. MediaGoblin is a suitable replacement for our
former free service. The only down side is how long a free media storage
option can realistically exist. But hats beyond the scope of this issue :).

On Friday, February 21, 2014, Jan-Christoph Borchardt <
notifications@github.com> wrote:

> @jmathai https://github.com/jmathai yeah, I know that, and I really
> appreciate that Trovebox is all still open source. The thing with Libre
> Projects though is that we have set ourselves some guidelines for what
> projects are included., like: open source, web app, nicely usable, hosted.
> 
> And one of them is that a hosted instance (or _the main_ hosted instance)
> should also offer a free plan (not just trial) - to ensure that also people
> without the means to pay for such a service can at least use a limited part
> of it.
> 
> I'm not asking you to offer up free-as-gratis plans, it's just that we
> decided for a strict set of requirements for inclusion on Libre Projects.
> Hope that clarifies it.
> 
> And yeah, maybe we could re-evaluate that decision. Or add one or two
> additional categories: >>No free plan available<< and >>No hosted instance<<.
> Then again, that would fill up the list with lots of projects which are on
> other lists with different focus already.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/libreprojects/libreprojects/issues/30#issuecomment-35710423
> .

## 

-- Snet form my mobl phoone

**Comment by jancborchardt** [comment]
Yeah, that’s a very good point. On the other hand, free storage space of the closed-source hosted solutions is thrown after people as well, even if they have paid plans. I’m not saying it’s good or necessary, but since that seems to be a big deciding factor for people (at least private customers), it might be good for hosted paid open source apps to have strategies which allow for similar solutions. That’s a key point in making them more approachable.

Anyway, keep up the awesome work Jaisen! :)
