### ISSUE TITLE
Tiny Tiny RSS

### ISSUE THREAD

**Issue by madbob** [libreprojects/libreprojects#32]
Add Tiny Tiny RSS, a web feed reader.
http://tt-rss.org/redmine/projects/tt-rss/wiki
Probably his place is under the section "News".

**Comment by jancborchardt** [comment]
@madbob as far as I know and can see from the website, Tiny Tiny RSS is not hosted anywhere. This makes it not eligible for Libre Projects, which is for »open source hosted web services«. Please let me know if there in fact is a hosted instance though.

In any case though, there’s already a really good feed reader on the site: [Newsblur](http://newsblur.com).

**Comment by lightonflux** [comment]
I hosted a instance, but its not public :D

Maybe libre projects needs a selfhosting category… Or a sister site for that purpose.

**Comment by jancborchardt** [comment]
One of the big reasons I started Libre Projects is that there are already a bunch of sites which list free web software, see [#7 similar directories and lists](https://github.com/libreprojects/libreprojects/issues/7) – but almost none of these indicate if there’s a readily hosted version, which is the most important part of what a web app is. Self-hosting is simply not an option for most people. If for using the software I am required to have my own server and know how to install code on it, it’s not really »free software«.

People need a solution, not options. That’s why we focus radically on web apps which are open source, hosted (with gratis plan available) and have good design & usability. And if there are multiple, evaluate which one is the best.

**Comment by lightonflux** [comment]
Thats true.

I didnt know much of these list. So thanks for that list.
