### ISSUE TITLE
ur1.ca

### ISSUE THREAD

**Issue by airon90** [libreprojects/libreprojects#39]
ur1.ca is a free URL shortner.

http://ur1.ca/cokua links to libreprojects.net
http://ur1.ca/cokuv links to libreprojects' new issue
http://ur1.ca/cokux links to libreprojects' source code

I already addedit in my pull req.
Do we add it?

**Comment by jancborchardt** [comment]
ur1.ca doesn’t mention »short link« in any way and also short links are really bad for the web and make links look shady. The tool which needs short links is identica/statusnet, and they use ur1.ca by default.

I’d say not add it.

**Comment by airon90** [comment]
«short links are really bad for the web» why?

**Comment by jancborchardt** [comment]
If ur1.ca goes down, all the links will be broken. Same thing happened to tr.im some years ago.

Links should only be shortened by the site the link points to itself. Say the New York Times would offer short links for their articles through nytim.es – then the link shortener and the source itself is operated by the same party, and both things will be either up or down. But never will the shortener be down independent from the website for the reason of it being an independent company.

**Comment by jancborchardt** [comment]
Thoughts on this URL shortening @jhuet @ironbishop @yuwash @lucab @sindikat?

**Comment by yuwash** [comment]
Yes it's definitely against the “unhosted” philosophy making the internet even more dependent on some centralized servers. However, the project [lilURL](http://sourceforge.net/projects/lilurl/) (that ur1.ca is based on) is quite active (last update 2013-04-19) and ur1.ca is completely free, so I can't find a strong reason to protest against it. As there are people regularly using url shorteners anyway, promoting free software for this isn't a too bad idea. The author of lilURL, @kenmickles , however, doesn't seem to maintain the project at github any longer.
One alternative is [TightURL](http://tighturl.com/project/p/tighturl/), GNU GPL 2, hosted at http://2tu.us
None of the two has got a really sophisticated design to compete with bit.ly etc. though. Additionally, they both don't have a logo (which would've been desirable for adding on the libreprojects site).

**Comment by kenmickles** [comment]
That lilURL SF project is definitely not very active. Not sure where they got the 2013-04-19 timestamp from, but I haven't looked at that code since 2005. I'm surprised it still exists/works.

**Comment by ironbishop** [comment]
URL shorteners _are_ bad, but the software is free and matchs the requirements for inclusion; so :+1: for ur1.ca. 

They provide their database for download, so if/when they go offline, it's still possible to know where a broken link was linking.

**Comment by lucab** [comment]
I'd say :+1: too. 

Moreover, in Debian we are also running our own shortner which is under a BSD-2 license: 
- http://deb.li/
- http://git.recluse.de/?p=debian/go.debian.net.git

On the ethics side, I can understand @jancborchardt worries, but I don't know how we could improve the status quo. IMHO, the main issue is that the {full-URL, short-URL} database is private and the services are not federated, so when one goes down all the references are lost. OTOH, making the DB fully public could be a privacy issue for users and overload the servers.

As a sidenote, same remarks hold for the plain-old-web: sites and pages go up and down, and it could happen that contents and references (as in URL and web-pages) get lost forever.

**Comment by airon90** [comment]
So, is this issue valid yet?
Is there some other @libreprojects/contributors who want to say his own opinion?

@yuwash: we can ask a logo to StatusNet. Otherwise, whe can just create a logo made just with the name of the service.

**Comment by jancborchardt** [comment]
I still think:
1. most services which need URL shorteners, like Twitter etc, already have one
2. URL shorteners destroy the web for reasons noted above, most notably linkrot

I’ll close this hence. :)

**Comment by yuwash** [comment]
+3. None of the known shorteners is really innovative so it would be worth showcasing.
