### ISSUE TITLE
Wikivoyage istead of Wikitravel

### ISSUE THREAD

**Issue by airon90** [libreprojects/libreprojects#40]
Wikitravel is a project bought by Internet Brands. So, I replaced it with Wikivoyage, a fork of Wikitravel maintained by Wikimedia Foundation.
It is added in my pull req.
Do we add it?

**Comment by jancborchardt** [comment]
Yes, replacing Wikitravel by Wikivoyage is great!

Btw, please make separate pull requests for each of these things, that makes it easier to discuss and separate concerns.

**Comment by jancborchardt** [comment]
@Airon90 your other pull request was closed as far as I remember because there was some other stuff in it as well. Do you want to open a new one and change Wikitravel to Wikivoyage, including the logo? Thanks!

**Comment by ironbishop** [comment]
fixed in #58
