### ISSUE TITLE
Wikidot is neither opensource nor free

### ISSUE THREAD

**Issue by yuwash** [libreprojects/libreprojects#41]
I didn't find any statement that the platform of wikidot.com is using any free software. Additionally, though this does offer a free-as-in-free-beer wiki hosting plan, there is considerable limitation including forced ads, so it can't really be called free/libre. The “unlimited” free subscription for “community sites” must undergo an intransparent approval process, whose criteria are not specified. See http://www.wikidot.com/plans

**Comment by jancborchardt** [comment]
Thanks for the notice! I checked their sites and apparently the source is at http://github.com/gabrys/wikidot, but that’s stale since more than 3 years, just like http://wikidot.org

Tweeted at them: https://twitter.com/jancborchardt/status/299441124202930176 cc @gabrys

**Comment by jancborchardt** [comment]
@yuwash thanks again for the note! Removed this as well, also sorry for the long wait. Ideally just issue a pull request yourself. :)
