### ISSUE TITLE
Song of Github

### ISSUE THREAD

**Issue by lightonflux** [libreprojects/libreprojects#42]
Service:
https://song-of-github.herokuapp.com/

Code:
https://github.com/ajacksified/song-of-github

License (MIT):
https://github.com/ajacksified/song-of-github/blob/master/LICENSE

**Comment by jancborchardt** [comment]
Haha, this is nice! Rather nerdy and not really a web app useful for many people or beyond one-time fun, so I’m closing this. Thanks for the hint though. ;)
