### ISSUE TITLE
mobile layout

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#49]
The current website doesn’t really work on mobile. We should adjust the CSS a bit to make it work. I guess it’s just some simple tweak to change the reflow, for instance that there are only always 2 or 3 projects next to each other per line – and we might even have to change the header style using a mobile media query.

Just thoughts for now. What do you think @jhuet @Airon90 @yuwash?

**Comment by ironbishop** [comment]
...we could learn a thing or two from http://thetoolbox.cc/ , it's a similar directory, but it's not focused on license.

**Comment by yuwash** [comment]
Started (no pull request yet): [default.css: search box modified for mobile-accessibility (Issue #49)](https://github.com/yuwash/libreprojects/commit/df4e9d09cf9f4df55e2e24283d7003c6449caaab)

**Comment by wrought** [comment]
I was tinkering with the same component. Need to adjust search error display as well. Overall, it seems to me a new header / search design would solve most of the mobile display issues.

**Comment by airon90** [comment]
@jancborchardt Sorry, I'm not good in CSS at all.
What do @libreprojects/contributors think about using Bootstrap?

**Comment by jancborchardt** [comment]
I think using Bootstrap is overkill. We need to adjust a bunch of styles anyway to make it look proper and not like »just another Bootstrap site«.

And anyway, the mobile layout is solved since a few months thanks to @wrought! :)
