### ISSUE TITLE
Piwigo

### ISSUE THREAD

**Issue by ghost** [libreprojects/libreprojects#64]
Host and share your photos with Piwigo
http://piwigo.org/

**Comment by jancborchardt** [comment]
As far as I can see Piwigo does not offer a hosted instance with a free
plan. That's a requirement for Libre Projects though because we want to
especially showcase the open source web software which makes it really easy
for people to use.

**Comment by yuwash** [comment]
A demonstration site does exist at http://piwigo.org/demo/ where you can register an account and comment on photos etc. Looking at the comments on photos, real interactions seem to be going on. (besides many tests)

**However**, as I tried, there's no way of uploading your own pictures. According to the doc, [Piwigo needs access to adminitration panel or ftp to upload pictures](http://piwigo.org/doc/doku.php?id=user_documentation:learn:add_picture).

**Comment by jancborchardt** [comment]
Yeah, a demo is not cutting it. Needs to provide full-fledged hosting.
