### ISSUE TITLE
pump.io

### ISSUE THREAD

**Issue by ghost** [libreprojects/libreprojects#65]
This is pump.io. It's a stream server that does most of what people really want from a social network.
http://pump.io/

**Comment by yuwash** [comment]
I suggest instead adding [Identi.ca](http://identi.ca), an installation of pump.io, recently moving from statusnet (I wonder why it's not already listed).

**Comment by airon90** [comment]
What @libreprojects/contributors think about adding identi.ca?

IMHO +1

**Comment by jancborchardt** [comment]
We actually did have identi.ca in the past, then signup wasn’t possible anymore. Now that it changed to pump.io I would agree we should add it back.

@Airon90 can you prepare a pull request? :)

**Comment by airon90** [comment]
Ok, but I can't create an icon!

**Comment by ironbishop** [comment]
merged
