### ISSUE TITLE
slid.es

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#66]
http://slid.es uses https://github.com/hakimel/reveal.js under the hood, has a free plan, and is web based.

**Comment by ironbishop** [comment]
great project :+1:

**Comment by yuwash** [comment]
Nice :+1: , why not add it!

**Comment by jancborchardt** [comment]
@yuwash do you want to add the data in the data.json and the logo as well? Would be cool if you can do a pull request for that. :)
