### ISSUE TITLE
LocalWiki!

### ISSUE THREAD

**Issue by mk30** [libreprojects/libreprojects#72]
Hi All,

Wonderful project! We'd love to have our project LocalWiki (localwiki.org) added. We're a collaborative open (open source and open content) knowledge project focused on local knowledge.
- Marina

**Comment by yuwash** [comment]
Yes, htat's not just a wiki, but it has a custom opensource software [localwiki/localwiki](https://github.com/localwiki/localwiki) and the license of the wiki contents (cc-by-sa 3.0 unported) is also perfectly free. :+1:

**Comment by ironbishop** [comment]
is it a mediawiki clone?

**Comment by mk30** [comment]
no, we developed a new OS wiki software specifically designed for collaboration in local communities. there's more info at http://localwiki.org/software/ and http://dev.localwiki.org/.

(please note that we're in the process of developing a new version of the software and will be deprecating the version described in the links above. there's a really long blog post about our future direction here: http://localwiki.org/blog/2013/jul/25/big-news-future-localwiki/)

**Comment by jancborchardt** [comment]
Hej Marina! I heard about LocalWiki before and quite like it!

Libre Projects is focused on _services_ though, not software you have to host on your own (as there are many platforms for that already, and an abundance of software). Do you provide wikis to people or do they have to set it up on their own? I didn’t quite understand that from http://localwiki.org/recommend_a_community/ :)

Cheers to the East Bay!

**Comment by mk30** [comment]
A ha, thanks for the clarification. We're currently transitioning away from the self-hosted software model towards a hosted platform model. Our new platform is still in alpha though (which explains the "recommend a community" form), so perhaps given the focus of your project, it might make more sense for us to be listed later, once we launch?

**Comment by jancborchardt** [comment]
Yeah, would be cool if you could let us know once you launch that! Just
comment here again, or ideally directly issue a pull request with the logo
and all. :)

**Comment by mk30** [comment]
Sounds good - will do!

**Comment by airon90** [comment]
Is this issue valid yet?

**Comment by mk30** [comment]
@Airon90 We're still developing our platform, so this project is not appropriate to add yet. But we're in alpha, so if you're interested in learning more about what we're doing and/or starting a LocalWiki in your community, check out http://localwiki.org.

**Comment by airon90** [comment]
Reopen an issue whan you want to add it.

**Comment by jancborchardt** [comment]
@mk30 yeah Marina, please let us know again when it’s appropriate to add. I heard of LocalWiki before and would love to add it as soon as it’s ready! :)
