### ISSUE TITLE
Loomio

### ISSUE THREAD

**Issue by jdaviescoates** [libreprojects/libreprojects#90]
loomio.org

**Comment by jancborchardt** [comment]
Hm, can you add a bit more info? Where’s the source, what’s the license, what’s a one-line description?

**Comment by jdaviescoates** [comment]
On 3 March 2014 15:56, Jan-Christoph Borchardt notifications@github.comwrote:

> Hm, can you add a bit more info? Where's the source

https://github.com/loomio/loomio (as fairly clearly linked to from
https://www.loomio.org/ homepage )

> , what's the license,

GNU AGPL
https://github.com/loomio/loomio/blob/master/LICENSE.txt

what's a one-line description?


From github:

""Loomio is an open-source web application that helps groups make better
decisions together."

From homepage (sounds like you perhaps didn't even bother to go there?!):

"collaborative decision-making"

"Loomio is a user-friendly tool for group decision-making.  Creating a
world where it's easy for anyone to participate in decisions that affect
them."

PS the same questions do actually apply to lots of the projects you're
currently listing to e.g. what is libre/ open about
http://onlinegroups.net/? they don't seem to mention anything about it
on their website and I can't
find the code anywhere either... same goes for quite a few of the projects
you list.

## 

Josef Davies-Coates
United Diversity

07974 88 88 95
http://uniteddiversity.coop

Follow us on Twitter http://twitter.com/uniteddiversity and
Facebookhttp://facebook.com/uniteddiversity

_Together We Have Everything_

**Comment by jancborchardt** [comment]
Can you submit a pull request for adding Loomio then? Including logo would be good. For the info you just need to edit the js/data.json

**Comment by jdaviescoates** [comment]
Sorry, I'm not yet a coder and don't yet really know how to use github - on
my list to learn this year though!

On 3 March 2014 17:47, Jan-Christoph Borchardt notifications@github.comwrote:

> Can you submit a pull request for adding Loomio then? Including logo would
> be good. For the info you just need to edit the js/data.json
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/libreprojects/libreprojects/issues/90#issuecomment-36536692
> .

## 

Josef Davies-Coates
United Diversity

07974 88 88 95
http://uniteddiversity.coop

Follow us on Twitter http://twitter.com/uniteddiversity and
Facebookhttp://facebook.com/uniteddiversity

_Together We Have Everything_

**Comment by jancborchardt** [comment]
@jdaviescoates cool! :) Check out http://try.github.io

**Comment by jdaviescoates** [comment]
Thanks! Will do :)

On 4 March 2014 12:01, Jan-Christoph Borchardt notifications@github.comwrote:

> @jdaviescoates https://github.com/jdaviescoates cool! :) Check out
> http://try.github.io
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/libreprojects/libreprojects/issues/90#issuecomment-36617448
> .

## 

Josef Davies-Coates
United Diversity

07974 88 88 95
http://uniteddiversity.coop

Follow us on Twitter http://twitter.com/uniteddiversity and
Facebookhttp://facebook.com/uniteddiversity

_Together We Have Everything_

**Comment by trolling42** [comment]
Is there any reason this has not been added. If you guys came to an agreement about adding this to the repo, I have added the file to social category and also added the logo.
