### ISSUE TITLE
Game: Untrusted

### ISSUE THREAD

**Issue by Daniel-at-github** [libreprojects/libreprojects#98]
A coding javascript game:
http://alexnisnevich.github.io/untrusted/

Good, if you like javascript.

**Comment by yuwash** [comment]
Sorry, I didn’t notice this. Any funny floss game is good, but I’m afraid
- it’s too geeky that the audience would be limited and
- the license is a bit restrictive (CC-BY-NC-SA) https://github.com/AlexNisnevich/untrusted

**Comment by jancborchardt** [comment]
Yup, I agree with @yuwash here.
